### ISSUE TITLE
Poprawić random z !hmmm

### ISSUE THREAD

**Issue by Chrrapek** [Chrrapek/DiscordMiejski#21]
Za często powtarzają się obrazki

**Comment by krasnoludkolo** [comment]
Brałbym dodatkowo z top tygodnia (co by były kłaliti) z kilku stron i losował z tego dopiero

**Comment by Chrrapek** [comment]
Ale to nie sprawi, że się będzie mniej powtarzało :p Top z tego tygodnia to jest niewiele obrazków

**Comment by Chrrapek** [comment]
Myślałem raczej o top z limit=None, żeby brać wszystko

**Comment by krasnoludkolo** [comment]
ewentualnie policzyć ile to jest 100 z tego topa i tyle brac,
