### ISSUE TITLE
!randomFromSub sub

### ISSUE THREAD

**Issue by krasnoludkolo** [Chrrapek/DiscordMiejski#22]

**Comment by Chrrapek** [comment]
Planuję to zrobić jako rozszerzenie !hmmm, a nie osobną komendę

**Comment by krasnoludkolo** [comment]
Chodzi mi, żeby zrobić jeden mechanizm do pobierania losowego zdj z dowolnego suba

**Comment by Chrrapek** [comment]
Nie jestem pewien, czy PRAW (libka od reddita) udostępnia możliwość sprawdzenia czy post zawiera zdjęcie. Do sprawdzenia
